### ISSUE TITLE
Allow to specify position of controls in desktop mode

### ISSUE THREAD

**Issue by Sohalt** [lijinke666/react-music-player#189]
### Description
To me it feels a little unnatural to have the playback controls sort of "hidden" in the bottom right corner of the screen. It would be nice to have a way to move the playback controls to the left of the seek bar, or, even better, to move them to the center and have the seek bar be a separate row.

**Comment by lijinke666** [comment]
I think it's a UI design issue, different players have different designs, i think you want use the design 
![image](https://user-images.githubusercontent.com/21015895/95670902-d5e4c500-0bc3-11eb-9e0f-5f67226688c7.png)

but i don't want change current player UI design, the player is a base component, everyone's favorite style is different, and they can't all be satisfied, also don't provide some themes, like `<ReactJkMusicPlayer  layout="layout1 | layout2 | layout3"/>`

Of course, why not to use css to modify the player style? i think you can overwrite the player class names for custom UI design, rather than having the player adapt to everyone's needs.

**Comment by Sohalt** [comment]
Fair enough. I pretty much precisely want what you have in your Screenshot. Did you get that with just some CSS?
