### ISSUE TITLE
Start playlist from first track

### ISSUE THREAD

**Issue by chaos87** [lijinke666/react-music-player#286]
Hi,

With autoPlayInitLoadPlayList=true
If I play second song of playlist A and update audioLists with songs from playlist B then it does not start from beginning but from index of current song that was played from playlist A (second position)

I could reproduce this behavior on the demo site https://react-jinke-music-player.netlify.app/
Tick the box for autoPlayInitLoadPlayList=true, click play and then click to load the second playlist it will start from song 2 and not song 1.

How can I have the player always start the playlist from first index or song 1? Thanks!

**Comment by lijinke666** [comment]
Cannot reproduce
https://user-images.githubusercontent.com/21015895/105968090-96ce7700-60c1-11eb-9767-492be7255b21.mp4

**Comment by chaos87** [comment]
A screen recording is worth a billion words
See when I switch to playlist 2, it starts from track 2

https://user-images.githubusercontent.com/30872370/105972770-ef544300-60c6-11eb-87d1-9685afb311dc.mov

**Comment by deluan** [comment]
Hey @lijinke666 , this fix (e42177b187bd0a56914d0c59d0db2113fd694867) caused an issue with `quietUpdate`: If the song playing is not the first, when I change the `audioLists`, `playIndex` resets back to 0. I can confirm this bug was introduced in 4.21.2. Please check the recording:

https://user-images.githubusercontent.com/331353/124370226-f9183e80-dc42-11eb-9612-fa7347993d0f.mov
