### ISSUE TITLE
Safari & iOs browsers bug with big size songs

### ISSUE THREAD

**Issue by SpiritMod** [lijinke666/react-music-player#339]
### Version
4.21.1

### Description
Unexpected player behavior in Safari

### Steps
1) Open page https://dev.podcasts.pm 
2) wait 5-15 seconds and you will see errors in the console and the player will switch tracks in the playlist

### Reproduce Link
https://dev.podcasts.pm

<img width="1438" alt="Знімок екрана 2021-03-26 о 14 20 22" src="https://user-images.githubusercontent.com/6351540/112630577-719a8280-8e3e-11eb-9bde-73d9e4d467a3.png">

### System information
macOs Catalina 10.15.6, browser Safari 13.1.2

### Comments
If you set a playlist with audio files smaller than 30 MB to the player, everything works correctly

**Comment by bartzushka** [comment]
I have same issue with safari on both mac os and ios. But same functionality is ok in other players for example simplecast player

**Comment by bartzushka** [comment]
@lijinke666 hey do you have any suggestions here? The problem is with loading big audio and appears only in safari browsers for both macos and ios. The problem I think is associated with loading partial content audio with status 206. 
When you are trying to start playing such tracks the player load first part of bytes plays a little time and then triggers next audio. 
This can be easily checked with this audio file in Safari browser : https://cdn.simplecast.com/audio/746a01/746a0177-ec4c-461d-b7ed-4a100793e9d0/c881ee09-386d-4fbe-a7d7-422db1756b3b/podcast-2_tc.mp3

**Comment by lijinke666** [comment]
Thank your feedback, right now, I'm too busy to deal with open source projects, can you try to seed a PR for fixed the bug?

**Comment by lijinke666** [comment]
1. please upgrade latest version (4.23.0), the version optimized https://github.com/lijinke666/react-music-player/blob/7f4e19ef60752f4f37718ea361068c33892e90cd/src/index.js#L1760
https://developers.google.com/web/updates/2017/06/play-request-was-interrupted
2. NotAllowError: Safari and iOS disable auto play now. this is a platform limitation, so suggestion use `autoPlay:false` or set audio muted

**Comment by lijinke666** [comment]
https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
