### ISSUE TITLE
iOS issues

### ISSUE THREAD

**Issue by Aeyzaz** [lijinke666/react-music-player#64]
on iOS, 
1 . autoplay isn't working.
2. Seekbar shows NAN on total time.

**Comment by lijinke666** [comment]
> 1 . autoplay isn't working.
IOS 9 + , audio autoplay is disabled, must be user trigger . like clicked a button to play song.
I've optimized it in a number of ways. so autoplay isn't working

2. Seekbar shows NAN on total time.
please tell me more detail. like audio duration ? audio size? did the audio load fail? what error message does the console print?  use `onAudioLoadError `

**Comment by Aeyzaz** [comment]
Unfortunately the error is only on iPhone have a look
![scresht](https://user-images.githubusercontent.com/6577735/67520141-b6f2d780-f6c1-11e9-8049-b0e912ef031f.jpg)

**Comment by Aeyzaz** [comment]
Can you please roll out some update for this?

**Comment by lijinke666** [comment]
I have tested iphone6s and iphone x and found no problem. Please give me an online url, otherwise I don't know how to solve it, like `codesandbox`

**Comment by Aeyzaz** [comment]
peanutplayer.com

**Comment by lijinke666** [comment]
![image](https://user-images.githubusercontent.com/21015895/68284079-c1e13b00-00b7-11ea-927b-a639ade68517.png)
Conversion failed to play the song

**Comment by Aeyzaz** [comment]
Its works with YouTube only, please use YouTube video

**Comment by lijinke666** [comment]
please give me a valid video url

**Comment by Aeyzaz** [comment]
https://youtu.be/Pkh8UtuejGw

**Comment by lijinke666** [comment]
http://35.181.31.64:3478/watch?v=Pkh8UtuejGw
Because the browser cannot get this song  duration
![image](https://user-images.githubusercontent.com/21015895/68285976-41bcd480-00bb-11ea-9ff2-eae2e4cf8095.png)

open the resource
![image](https://user-images.githubusercontent.com/21015895/68285809-ed195980-00ba-11ea-8248-0ae5d754a565.png)

your audio response type
![image](https://user-images.githubusercontent.com/21015895/68286141-85174300-00bb-11ea-907a-25ba2eefa9d0.png)


My audio format is mp3 so it parses normally
![image](https://user-images.githubusercontent.com/21015895/68285884-0cb08200-00bb-11ea-8460-a1ef6e63a15e.png)

![image](https://user-images.githubusercontent.com/21015895/68286172-96f8e600-00bb-11ea-92d9-3829662d3f89.png)


so. cannot get duration It has to do with the format of your audio 
It has nothing to do with the player

**Comment by lijinke666** [comment]
And I have some Suggestions
This is just a project of my hobby, because I like music
But if you have a problem like this, you can try to solve it
After all, I don't have much time
because this is just to play some music
There is no way to meet all the business needs

Finally, thank you for using this player
