### ISSUE TITLE
Feature: Playback at different speed

### ISSUE THREAD

**Issue by houmark** [lijinke666/react-music-player#65]
Hi,

Nice player.

I'm considering to use this player for non-music files (recordings).

HTML5 audio supports playing a different speeds with `setPlaybackRate(2)` for double speed for example.

Would you consider adding that with a UI button to change speed?

The UI button could be configured with an array of objects setting the speed and the label for the button.

**Comment by lijinke666** [comment]
Hi . ok.  good idea , If I have time recently, I will add it. Of course, welcome pr

**Comment by houmark** [comment]
Sounds great. If I have a chance to try doing a PR, I will let you know here so we both work on it at the same time. If you start, please also let me know ;)

**Comment by lijinke666** [comment]
update `v4.5.0`   use `getAudioInstance`

with `extendsContent` add your custom UI use the `instance` (HTMLMediaElement) to do anything

[HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement)

> example

```tsx
  let audio
  <ReactJkMusicPlayer 
    getAudioInstance = {(instance) => {
        audio = instance
      }
   }
   extendsContent: [
      <button onClick={()=> audio.playbackRate = 2}>
          set playback rate
      </button>
    ]
  />
  ```

**If you want to use a feature welcome PR instead of waiting for me to add the feature you want**

**Comment by houmark** [comment]
This also works great and opens for a lot of extensibility so great direction you took on this one. And fast! Thank you!
